name: bottom_nav
description: A Flutter BottomNavigation package with extra functions and flexibility and ease of usage.
version: 0.0.1
homepage: 'https://github.com/kenresoft/bottom_nav'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  extensionresoft: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
